version: "3.4"

services:
  #Currently not using dokcer-compose to deploy
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdkfjhaksjdhfgkahe
      POSTGRES_DB: LimbusCompanyIDMaker
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  webapi:
    image: server/server:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: on-failure
    environment:
      - TokenEndpoint=${TokenEndpoint}
      - SessionExpiredDay=${SessionExpiredDay}
      - DefaultConnection=${DefaultConnection}
      - RemoteConnection=${RemoteConnection}
      - FrontendUri=${FrontendUri}
      - CookieSessionProtectorSecret=${CookieSessionProtectorSecret}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_HOST_USER_NAME=${RABBITMQ_HOST_USER_NAME}
      - RABBITMQ_PASSWORD=${g8gLlNCy-c6dJL52IRhPWdJ2Md2oviOy}
      - RABBITMQ_VH=${RABBITMQ_VH}
      - CLOUDINARY_IMG_URL_START=${CLOUDINARY_IMG_URL_START}
      - MODE=${MODE}
      - LISTEN_ON=${LISTEN_ON}
volumes:
  pgdata: